// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _3NF_Library.Data.Context;

#nullable disable

namespace _3NF_Library.Data.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("seq_Author");

            modelBuilder.HasSequence("seq_Publisher");

            modelBuilder.Entity("_3NF_Library.Models.Entities.tbl_ActivityLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<int>("ActorID")
                        .HasColumnType("int");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LogMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("LogID")
                        .HasName("PK__tbl_Acti__5E5499A81C57E284");

                    b.ToTable("tbl_ActivityLog");
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.tbl_Admin_Account", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("AdminID")
                        .HasName("PK__tbl_Admi__719FE4E8ECFCD79F");

                    b.HasIndex(new[] { "Username" }, "UQ__tbl_Admi__536C85E476F99257")
                        .IsUnique();

                    b.ToTable("tbl_Admin_Account");
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.tbl_Attendance", b =>
                {
                    b.Property<int>("AttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<string>("AccountRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("CheckInTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("AttendanceID")
                        .HasName("PK__tbl_Atte__8B69263C0008E528");

                    b.ToTable("tbl_Attendance");
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.tbl_Author", b =>
                {
                    b.Property<string>("AuthorID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValueSql("('TG'+right('00000'+CONVERT([varchar](5),NEXT VALUE FOR [seq_Author]),(5)))");

                    b.Property<DateOnly?>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AuthorID")
                        .HasName("PK__tbl_Auth__70DAFC14F3E0DB7C");

                    b.HasIndex(new[] { "LastName", "FirstName" }, "IDX_AuthorName");

                    b.ToTable("tbl_Author", null, t =>
                        {
                            t.HasTrigger("trg_PreventAuthorDelete");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.tbl_Book", b =>
                {
                    b.Property<string>("BookID")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("AuthorID")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("PublishedDate")
                        .HasColumnType("date");

                    b.Property<string>("PublisherID")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long?>("Value")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("BookID")
                        .HasName("PK__tbl_Book__3DE0C227F201C9BA");

                    b.HasIndex("AuthorID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("PublisherID");

                    b.HasIndex(new[] { "BookTitle" }, "IDX_BookTitle");

                    b.ToTable("tbl_Book", null, t =>
                        {
                            t.HasTrigger("trg_InsertBook");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.tbl_Borrow_Detail", b =>
                {
                    b.Property<int>("DetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailID"));

                    b.Property<string>("BookID")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int?>("OrderID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Borrowing");

                    b.HasKey("DetailID")
                        .HasName("PK__tbl_Borr__135C314DDA07383D");

                    b.HasIndex("BookID");

                    b.HasIndex("OrderID");

                    b.ToTable("tbl_Borrow_Detail", null, t =>
                        {
                            t.HasTrigger("trg_ManageBookInventory");

                            t.HasTrigger("trg_PreventEmptyOrder");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.tbl_Borrow_Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<DateOnly?>("DateBorrow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("DateReturn")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<int?>("ReaderID")
                        .HasColumnType("int");

                    b.HasKey("OrderID")
                        .HasName("PK__tbl_Borr__C3905BAF21FA1906");

                    b.HasIndex("ReaderID");

                    b.ToTable("tbl_Borrow_Order", null, t =>
                        {
                            t.HasTrigger("trg_SyncOrderStatus_To_Detail");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.tbl_Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("CategoryID")
                        .HasName("PK__tbl_Cate__19093A2B450E4A15");

                    b.HasIndex(new[] { "ShortName" }, "UQ__tbl_Cate__A6160FD14E284F43")
                        .IsUnique();

                    b.ToTable("tbl_Category");
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.tbl_Fine", b =>
                {
                    b.Property<int>("FineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FineID"));

                    b.Property<long?>("Amount")
                        .HasColumnType("bigint");

                    b.Property<int?>("DetailID")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Unpaid");

                    b.HasKey("FineID")
                        .HasName("PK__tbl_Fine__9D4A9BCC67C221AF");

                    b.HasIndex("DetailID");

                    b.ToTable("tbl_Fine", null, t =>
                        {
                            t.HasTrigger("trg_LogFinePayment");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.tbl_Librarian_Account", b =>
                {
                    b.Property<int>("LibrarianID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LibrarianID"));

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("LibrarianID")
                        .HasName("PK__tbl_Libr__E4D86D9D029EEAE1");

                    b.HasIndex(new[] { "Username" }, "UQ__tbl_Libr__536C85E48F78F773")
                        .IsUnique();

                    b.ToTable("tbl_Librarian_Account");
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.tbl_Publisher", b =>
                {
                    b.Property<string>("PublisherID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValueSql("('NXB'+right('00000'+CONVERT([varchar](5),NEXT VALUE FOR [seq_Publisher]),(5)))");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PublisherID")
                        .HasName("PK__tbl_Publ__4C657E4B6D2B2745");

                    b.ToTable("tbl_Publisher", null, t =>
                        {
                            t.HasTrigger("trg_PreventPublisherDelete");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.tbl_Reader_Account", b =>
                {
                    b.Property<int>("ReaderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReaderID"));

                    b.Property<DateOnly?>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("MemberSince")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Organization")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("1223334444");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReaderID")
                        .HasName("PK__tbl_Read__8E67A5812D9BCACD");

                    b.HasIndex(new[] { "LastName", "FirstName" }, "IDX_ReaderName");

                    b.ToTable("tbl_Reader_Account");
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.vw_Admin_BorrowStat", b =>
                {
                    b.Property<int?>("CurrentlyBorrowed")
                        .HasColumnType("int");

                    b.Property<int?>("TotalLifetimeBorrows")
                        .HasColumnType("int");

                    b.Property<int?>("TotalLost")
                        .HasColumnType("int");

                    b.Property<int?>("TotalOverdue")
                        .HasColumnType("int");

                    b.Property<int?>("TotalReturned")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_Admin_BorrowStats", (string)null);
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.vw_Admin_Financial", b =>
                {
                    b.Property<long?>("PendingRevenue")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalRevenueCollected")
                        .HasColumnType("bigint");

                    b.ToTable((string)null);

                    b.ToView("vw_Admin_Financials", (string)null);
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.vw_Book_Public", b =>
                {
                    b.Property<string>("AuthorID")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(101)
                        .HasColumnType("nvarchar(101)");

                    b.Property<string>("BookID")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CurrentlyAvailable")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("PublishedDate")
                        .HasColumnType("date");

                    b.Property<string>("PublisherID")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PublisherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Value")
                        .HasColumnType("bigint");

                    b.ToTable((string)null);

                    b.ToView("vw_Book_Public", (string)null);
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.tbl_Book", b =>
                {
                    b.HasOne("_3NF_Library.Models.Entities.tbl_Author", "Author")
                        .WithMany("tbl_Books")
                        .HasForeignKey("AuthorID")
                        .HasConstraintName("FK__tbl_Book__Author__619B8048");

                    b.HasOne("_3NF_Library.Models.Entities.tbl_Category", "Category")
                        .WithMany("tbl_Books")
                        .HasForeignKey("CategoryID")
                        .HasConstraintName("FK__tbl_Book__Catego__6383C8BA");

                    b.HasOne("_3NF_Library.Models.Entities.tbl_Publisher", "Publisher")
                        .WithMany("tbl_Books")
                        .HasForeignKey("PublisherID")
                        .HasConstraintName("FK__tbl_Book__Publis__628FA481");

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.tbl_Borrow_Detail", b =>
                {
                    b.HasOne("_3NF_Library.Models.Entities.tbl_Book", "Book")
                        .WithMany("tbl_Borrow_Details")
                        .HasForeignKey("BookID")
                        .HasConstraintName("FK__tbl_Borro__BookI__74AE54BC");

                    b.HasOne("_3NF_Library.Models.Entities.tbl_Borrow_Order", "Order")
                        .WithMany("tbl_Borrow_Details")
                        .HasForeignKey("OrderID")
                        .HasConstraintName("FK__tbl_Borro__Order__73BA3083");

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.tbl_Borrow_Order", b =>
                {
                    b.HasOne("_3NF_Library.Models.Entities.tbl_Reader_Account", "Reader")
                        .WithMany("tbl_Borrow_Orders")
                        .HasForeignKey("ReaderID")
                        .HasConstraintName("FK__tbl_Borro__Reade__6EF57B66");

                    b.Navigation("Reader");
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.tbl_Fine", b =>
                {
                    b.HasOne("_3NF_Library.Models.Entities.tbl_Borrow_Detail", "Detail")
                        .WithMany("tbl_Fines")
                        .HasForeignKey("DetailID")
                        .HasConstraintName("FK__tbl_Fine__Detail__787EE5A0");

                    b.Navigation("Detail");
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.tbl_Author", b =>
                {
                    b.Navigation("tbl_Books");
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.tbl_Book", b =>
                {
                    b.Navigation("tbl_Borrow_Details");
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.tbl_Borrow_Detail", b =>
                {
                    b.Navigation("tbl_Fines");
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.tbl_Borrow_Order", b =>
                {
                    b.Navigation("tbl_Borrow_Details");
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.tbl_Category", b =>
                {
                    b.Navigation("tbl_Books");
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.tbl_Publisher", b =>
                {
                    b.Navigation("tbl_Books");
                });

            modelBuilder.Entity("_3NF_Library.Models.Entities.tbl_Reader_Account", b =>
                {
                    b.Navigation("tbl_Borrow_Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
