// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using _3NF_Library.Models.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace _3NF_Library.Data.Context
{
    public partial interface ILibraryDbContextProcedures
    {
        Task<List<sp_Accounting_GetPaidFinesResult>?> sp_Accounting_GetPaidFinesAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_Accounting_GetUnpaidFinesResult>?> sp_Accounting_GetUnpaidFinesAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_Accounting_PayFineResult>?> sp_Accounting_PayFineAsync(int? fineID, int? librarianID, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> sp_AddAuthorAsync(string? firstName, string? lastName, DateOnly? dOB, string? description, string? specialty, int? librarianID, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_AddCategoryResult>?> sp_AddCategoryAsync(string? categoryName, string? shortName, int? librarianID, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> sp_AddNewBookAsync(string? language, string? bookTitle, string? authorID, string? publisherID, int? categoryID, DateOnly? publishedDate, int? quantity, long? value, int? librarianID, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> sp_AddPublisherAsync(string? address, string? description, int? librarianID, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_Admin_AddNewLibrarianResult>?> sp_Admin_AddNewLibrarianAsync(string? username, string? password, string? fullName, string? branch, int? adminID, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_Admin_GetActivityLogsResult>?> sp_Admin_GetActivityLogsAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_BorrowList_AllResult>?> sp_BorrowList_AllAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> sp_CheckAndApplyDueFinesAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_CheckInResult>?> sp_CheckInAsync(string? accountRole, int? accountID, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> sp_CreateBorrowOrderAsync(int? librarianID, int? readerID, int? daysToBorrow, string? bookList, string? notes, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> sp_CreateReaderAccountAsync(string? firstName, string? lastName, DateOnly? dOB, string? organization, string? status, string? role, int? librarianID, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_FindBookByAuthorResult>?> sp_FindBookByAuthorAsync(string? authorName, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_FindBookByCategoryResult>?> sp_FindBookByCategoryAsync(string? categoryName, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_FindBookByPublishedYearResult>?> sp_FindBookByPublishedYearAsync(int? year, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_FindBookByPublisherResult>?> sp_FindBookByPublisherAsync(string? publisherName, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_FindBookByTitleResult>?> sp_FindBookByTitleAsync(string? title, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_FindReaderByNameResult>?> sp_FindReaderByNameAsync(string? searchKeyword, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_FindReaderByOrganizationResult>?> sp_FindReaderByOrganizationAsync(string? organization, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_findReaderByRoleResult>?> sp_findReaderByRoleAsync(string? role, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_GetAllAuthorResult>?> sp_GetAllAuthorAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_GetAllBookResult>?> sp_GetAllBookAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_GetAllOrganizationsResult>?> sp_GetAllOrganizationsAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_GetAllPublisherResult>?> sp_GetAllPublisherAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_GetDatabaseInventoryResult>?> sp_GetDatabaseInventoryAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_getReaderListResult>?> sp_getReaderListAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_Librarian_ApproveOrderResult>?> sp_Librarian_ApproveOrderAsync(int? orderID, int? librarianID, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_Librarian_GetBorrowingOrdersResult>?> sp_Librarian_GetBorrowingOrdersAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_Librarian_UpdateReaderInfoResult>?> sp_Librarian_UpdateReaderInfoAsync(int? readerID, string? firstName, string? lastName, DateOnly? dOB, string? organization, string? status, string? role, string? phone, int? librarianID, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_LogInResult>?> sp_LogInAsync(string? accountType, string? username, string? password, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> sp_MarkBookLostAndUpdateFineAsync(int? detailID, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> sp_PayFineAsync(int? fineID, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_Reader_CreatePendingOrderResult>?> sp_Reader_CreatePendingOrderAsync(int? readerID, int? daysToBorrow, string? bookList, string? notes, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_Reader_GetAllMyInfoResult>?> sp_Reader_GetAllMyInfoAsync(int? readerID, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_Reader_UpdatePasswordResult>?> sp_Reader_UpdatePasswordAsync(int? readerID, string? oldPassword, string? newPassword, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<sp_Reader_UpdatePhoneResult>?> sp_Reader_UpdatePhoneAsync(int? readerID, string? phone, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> sp_ReturnBookAsync(int? detailID, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> sp_UpdateReaderInfoAsync(int? readerID, string? firstName, string? lastName, DateOnly? dOB, string? organization, string? status, string? role, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
    }
}
