// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using _3NF_Library.Models.Entities;
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;


namespace _3NF_Library.Data.Context;

public partial class LibraryDbContext : DbContext
{
    public LibraryDbContext(DbContextOptions<LibraryDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<tbl_ActivityLog> tbl_ActivityLogs { get; set; }

    public virtual DbSet<tbl_Admin_Account> tbl_Admin_Accounts { get; set; }

    public virtual DbSet<tbl_Attendance> tbl_Attendances { get; set; }

    public virtual DbSet<tbl_Author> tbl_Authors { get; set; }

    public virtual DbSet<tbl_Book> tbl_Books { get; set; }

    public virtual DbSet<tbl_Borrow_Detail> tbl_Borrow_Details { get; set; }

    public virtual DbSet<tbl_Borrow_Order> tbl_Borrow_Orders { get; set; }

    public virtual DbSet<tbl_Category> tbl_Categories { get; set; }

    public virtual DbSet<tbl_Fine> tbl_Fines { get; set; }

    public virtual DbSet<tbl_Librarian_Account> tbl_Librarian_Accounts { get; set; }

    public virtual DbSet<tbl_Publisher> tbl_Publishers { get; set; }

    public virtual DbSet<tbl_Reader_Account> tbl_Reader_Accounts { get; set; }

    public virtual DbSet<vw_Admin_BorrowStat> vw_Admin_BorrowStats { get; set; }

    public virtual DbSet<vw_Admin_Financial> vw_Admin_Financials { get; set; }

    public virtual DbSet<vw_Book_Public> vw_Book_Publics { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<tbl_ActivityLog>(entity =>
        {
            entity.HasKey(e => e.LogID).HasName("PK__tbl_Acti__5E5499A81C57E284");

            entity.Property(e => e.Timestamp).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<tbl_Admin_Account>(entity =>
        {
            entity.HasKey(e => e.AdminID).HasName("PK__tbl_Admi__719FE4E8ECFCD79F");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<tbl_Attendance>(entity =>
        {
            entity.HasKey(e => e.AttendanceID).HasName("PK__tbl_Atte__8B69263C0008E528");

            entity.Property(e => e.CheckInTime).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<tbl_Author>(entity =>
        {
            entity.HasKey(e => e.AuthorID).HasName("PK__tbl_Auth__70DAFC14F3E0DB7C");

            entity.ToTable("tbl_Author", tb => tb.HasTrigger("trg_PreventAuthorDelete"));

            entity.Property(e => e.AuthorID).HasDefaultValueSql("('TG'+right('00000'+CONVERT([varchar](5),NEXT VALUE FOR [seq_Author]),(5)))");
        });

        modelBuilder.Entity<tbl_Book>(entity =>
        {
            entity.HasKey(e => e.BookID).HasName("PK__tbl_Book__3DE0C227F201C9BA");

            entity.ToTable("tbl_Book", tb => tb.HasTrigger("trg_InsertBook"));

            entity.Property(e => e.Quantity).HasDefaultValue(0);
            entity.Property(e => e.Value).HasDefaultValue(0L);

            entity.HasOne(d => d.Author).WithMany(p => p.tbl_Books).HasConstraintName("FK__tbl_Book__Author__619B8048");

            entity.HasOne(d => d.Category).WithMany(p => p.tbl_Books).HasConstraintName("FK__tbl_Book__Catego__6383C8BA");

            entity.HasOne(d => d.Publisher).WithMany(p => p.tbl_Books).HasConstraintName("FK__tbl_Book__Publis__628FA481");
        });

        modelBuilder.Entity<tbl_Borrow_Detail>(entity =>
        {
            entity.HasKey(e => e.DetailID).HasName("PK__tbl_Borr__135C314DDA07383D");

            entity.ToTable("tbl_Borrow_Detail", tb =>
                {
                    tb.HasTrigger("trg_ManageBookInventory");
                    tb.HasTrigger("trg_PreventEmptyOrder");
                });

            entity.Property(e => e.Status).HasDefaultValue("Borrowing");

            entity.HasOne(d => d.Book).WithMany(p => p.tbl_Borrow_Details).HasConstraintName("FK__tbl_Borro__BookI__74AE54BC");

            entity.HasOne(d => d.Order).WithMany(p => p.tbl_Borrow_Details).HasConstraintName("FK__tbl_Borro__Order__73BA3083");
        });

        modelBuilder.Entity<tbl_Borrow_Order>(entity =>
        {
            entity.HasKey(e => e.OrderID).HasName("PK__tbl_Borr__C3905BAF21FA1906");

            entity.ToTable("tbl_Borrow_Order", tb => tb.HasTrigger("trg_SyncOrderStatus_To_Detail"));

            entity.Property(e => e.DateBorrow).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.OrderStatus).HasDefaultValue("Pending");

            entity.HasOne(d => d.Reader).WithMany(p => p.tbl_Borrow_Orders).HasConstraintName("FK__tbl_Borro__Reade__6EF57B66");
        });

        modelBuilder.Entity<tbl_Category>(entity =>
        {
            entity.HasKey(e => e.CategoryID).HasName("PK__tbl_Cate__19093A2B450E4A15");
        });

        modelBuilder.Entity<tbl_Fine>(entity =>
        {
            entity.HasKey(e => e.FineID).HasName("PK__tbl_Fine__9D4A9BCC67C221AF");

            entity.ToTable("tbl_Fine", tb => tb.HasTrigger("trg_LogFinePayment"));

            entity.Property(e => e.Status).HasDefaultValue("Unpaid");

            entity.HasOne(d => d.Detail).WithMany(p => p.tbl_Fines).HasConstraintName("FK__tbl_Fine__Detail__787EE5A0");
        });

        modelBuilder.Entity<tbl_Librarian_Account>(entity =>
        {
            entity.HasKey(e => e.LibrarianID).HasName("PK__tbl_Libr__E4D86D9D029EEAE1");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<tbl_Publisher>(entity =>
        {
            entity.HasKey(e => e.PublisherID).HasName("PK__tbl_Publ__4C657E4B6D2B2745");

            entity.ToTable("tbl_Publisher", tb => tb.HasTrigger("trg_PreventPublisherDelete"));

            entity.Property(e => e.PublisherID).HasDefaultValueSql("('NXB'+right('00000'+CONVERT([varchar](5),NEXT VALUE FOR [seq_Publisher]),(5)))");
        });

        modelBuilder.Entity<tbl_Reader_Account>(entity =>
        {
            entity.HasKey(e => e.ReaderID).HasName("PK__tbl_Read__8E67A5812D9BCACD");

            entity.Property(e => e.MemberSince).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Password).HasDefaultValue("1223334444");
        });

        modelBuilder.Entity<vw_Admin_BorrowStat>(entity =>
        {
            entity.ToView("vw_Admin_BorrowStats");
        });

        modelBuilder.Entity<vw_Admin_Financial>(entity =>
        {
            entity.ToView("vw_Admin_Financials");
        });

        modelBuilder.Entity<vw_Book_Public>(entity =>
        {
            entity.ToView("vw_Book_Public");
        });
        modelBuilder.HasSequence("seq_Author");
        modelBuilder.HasSequence("seq_Publisher");

        OnModelCreatingGeneratedFunctions(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}