// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using _3NF_Library.Models.Entities;

namespace _3NF_Library.Data.Context
{
    public partial class LibraryDbContext
    {

        [DbFunction("fn_CalculateFine", "dbo")]
        public static long? fn_CalculateFine(long? BookValue, string ReaderRole, bool? IsLost)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
