// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace _3NF_Library.Models.Entities
{
    public partial class sp_Admin_GetActivityLogsResult
    {
        public int LogID { get; set; }
        [StringLength(4000)]
        public string? Time { get; set; }
        [StringLength(20)]
        public string Role { get; set; } = default!;
        public int ID { get; set; }
        [Column("Nội dung hoạt động")]
        [StringLength(2147483647)]
        public string Nộidunghoạtđộng { get; set; } = default!;
    }
}
