// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace _3NF_Library.Models.Entities
{
    public partial class sp_Accounting_GetUnpaidFinesResult
    {
        public int FineID { get; set; }
        public int ReaderID { get; set; }
        [StringLength(101)]
        public string ReaderName { get; set; } = default!;
        public long? Amount { get; set; }
        [StringLength(255)]
        public string? Reason { get; set; }
        [StringLength(4000)]
        public string? BorrowDate { get; set; }
    }
}
