// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace _3NF_Library.Models.Entities
{
    public partial class sp_Accounting_GetPaidFinesResult
    {
        public int FineID { get; set; }
        [StringLength(101)]
        public string ReaderName { get; set; } = default!;
        public long? Amount { get; set; }
        [StringLength(6)]
        public string Status { get; set; } = default!;
        [StringLength(8)]
        public string CollectedBy { get; set; } = default!;
    }
}