// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace _3NF_Library.Models.Entities
{
    public partial class sp_BorrowList_AllResult
    {
        public int OrderID { get; set; }
        [StringLength(101)]
        public string ReaderName { get; set; } = default!;
        [StringLength(200)]
        public string BookTitle { get; set; } = default!;
        [StringLength(50)]
        public string? BookStatus { get; set; }
        public DateOnly? DateBorrow { get; set; }
        public DateOnly? DateReturn { get; set; }
        public long FineAmount { get; set; }
        [StringLength(50)]
        public string FineStatus { get; set; } = default!;
    }
}
