// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace _3NF_Library.Models.Entities
{
    public partial class sp_CheckInResult
    {
        public DateTime? CheckInTime { get; set; }
        [StringLength(50)]
        public string? AttendanceStatus { get; set; }
    }
}
