// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace _3NF_Library.Models.Entities
{
    public partial class sp_FindReaderByOrganizationResult
    {
        [StringLength(101)]
        public string Tên { get; set; } = default!;
        [Column("Số điện thoại")]
        [StringLength(15)]
        public string? Sốđiệnthoại { get; set; }
        public DateOnly? dob { get; set; }
        [Column("Chức vụ")]
        [StringLength(50)]
        public string Chứcvụ { get; set; } = default!;
        [Column("Tổ chức")]
        [StringLength(100)]
        public string? Tổchức { get; set; }
        [StringLength(50)]
        public string? status { get; set; }
        public DateOnly? memberSince { get; set; }
    }
}
