// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace _3NF_Library.Models.Entities
{
    public partial class sp_FindBookByPublishedYearResult
    {
        [StringLength(15)]
        public string BookID { get; set; } = default!;
        [StringLength(50)]
        public string? Language { get; set; }
        [StringLength(200)]
        public string BookTitle { get; set; } = default!;
        [StringLength(10)]
        public string? AuthorID { get; set; }
        [StringLength(10)]
        public string? PublisherID { get; set; }
        public int? CategoryID { get; set; }
        public DateOnly? PublishedDate { get; set; }
        public long? Value { get; set; }
        public int? CurrentlyAvailable { get; set; }
        [StringLength(100)]
        public string CategoryName { get; set; } = default!;
        [StringLength(101)]
        public string AuthorName { get; set; } = default!;
        [StringLength(2147483647)]
        public string? PublisherName { get; set; }
    }
}
