// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace _3NF_Library.Models.Entities
{
    public partial class sp_GetAllAuthorResult
    {
        [StringLength(10)]
        public string AuthorID { get; set; } = default!;
        [StringLength(101)]
        public string AuthorName { get; set; } = default!;
        public DateOnly? DOB { get; set; }
        [StringLength(100)]
        public string? Specialty { get; set; }
    }
}
