// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace _3NF_Library.Models.Entities
{
    public partial class sp_GetAllBookResult
    {
        [StringLength(200)]
        public string BookTitle { get; set; } = default!;
        [StringLength(100)]
        public string? CategoryName { get; set; }
        [StringLength(50)]
        public string? Language { get; set; }
        [StringLength(101)]
        public string? AuthorName { get; set; }
        [StringLength(2147483647)]
        public string? PublisherName { get; set; }
        public int? CurrentlyAvailable { get; set; }
    }
}
