// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace _3NF_Library.Models.Entities
{
    public partial class sp_GetAllPublisherResult
    {
        [StringLength(10)]
        public string PublisherID { get; set; } = default!;
        [StringLength(2147483647)]
        public string? PublisherName { get; set; }
        [StringLength(255)]
        public string? Address { get; set; }
    }
}
