// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace _3NF_Library.Models.Entities
{
    public partial class sp_Librarian_GetBorrowingOrdersResult
    {
        public int OrderID { get; set; }
        [StringLength(101)]
        public string ReaderName { get; set; } = default!;
        public DateOnly? DateBorrow { get; set; }
        public DateOnly? Deadline { get; set; }
        [StringLength(4000)]
        public string? BookList { get; set; }
    }
}
