// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace _3NF_Library.Models.Entities;

[Table("tbl_Borrow_Detail")]
public partial class tbl_Borrow_Detail
{
    [Key]
    public int DetailID { get; set; }

    public int? OrderID { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string? BookID { get; set; }

    [StringLength(50)]
    public string? Status { get; set; }

    [ForeignKey("BookID")]
    [InverseProperty("tbl_Borrow_Details")]
    public virtual tbl_Book? Book { get; set; }

    [ForeignKey("OrderID")]
    [InverseProperty("tbl_Borrow_Details")]
    public virtual tbl_Borrow_Order? Order { get; set; }

    [InverseProperty("Detail")]
    public virtual ICollection<tbl_Fine> tbl_Fines { get; set; } = new List<tbl_Fine>();
}