// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace _3NF_Library.Models.Entities;

[Table("tbl_Fine")]
public partial class tbl_Fine
{
    [Key]
    public int FineID { get; set; }

    public int? DetailID { get; set; }

    [StringLength(255)]
    public string? Reason { get; set; }

    public long? Amount { get; set; }

    [StringLength(50)]
    public string? Status { get; set; }

    [ForeignKey("DetailID")]
    [InverseProperty("tbl_Fines")]
    public virtual tbl_Borrow_Detail? Detail { get; set; }
}