// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace _3NF_Library.Models.Entities;

[Table("tbl_Attendance")]
public partial class tbl_Attendance
{
    [Key]
    public int AttendanceID { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string AccountRole { get; set; } = null!;

    public int AccountID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CheckInTime { get; set; }
}