// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace _3NF_Library.Models.Entities;

[Table("tbl_Librarian_Account")]
[Index("Username", Name = "UQ__tbl_Libr__536C85E48F78F773", IsUnique = true)]
public partial class tbl_Librarian_Account
{
    [Key]
    public int LibrarianID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Username { get; set; } = null!;

    [StringLength(255)]
    [Unicode(false)]
    public string Password { get; set; } = null!;

    [StringLength(100)]
    public string FullName { get; set; } = null!;

    [StringLength(100)]
    public string Branch { get; set; } = null!;

    public bool? IsActive { get; set; }
}