// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace _3NF_Library.Models.Entities;

[Table("tbl_Book")]
[Index("BookTitle", Name = "IDX_BookTitle")]
public partial class tbl_Book
{
    [Key]
    [StringLength(15)]
    [Unicode(false)]
    public string BookID { get; set; } = null!;

    [StringLength(50)]
    public string? Language { get; set; }

    [StringLength(200)]
    public string BookTitle { get; set; } = null!;

    [StringLength(10)]
    [Unicode(false)]
    public string? AuthorID { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string? PublisherID { get; set; }

    public int? CategoryID { get; set; }

    public DateOnly? PublishedDate { get; set; }

    public int? Quantity { get; set; }

    public long? Value { get; set; }

    [ForeignKey("AuthorID")]
    [InverseProperty("tbl_Books")]
    public virtual tbl_Author? Author { get; set; }

    [ForeignKey("CategoryID")]
    [InverseProperty("tbl_Books")]
    public virtual tbl_Category? Category { get; set; }

    [ForeignKey("PublisherID")]
    [InverseProperty("tbl_Books")]
    public virtual tbl_Publisher? Publisher { get; set; }

    [InverseProperty("Book")]
    public virtual ICollection<tbl_Borrow_Detail> tbl_Borrow_Details { get; set; } = new List<tbl_Borrow_Detail>();
}