// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace _3NF_Library.Models.Entities;

[Table("tbl_Reader_Account")]
[Index("LastName", "FirstName", Name = "IDX_ReaderName")]
public partial class tbl_Reader_Account
{
    [Key]
    public int ReaderID { get; set; }

    [StringLength(50)]
    public string FirstName { get; set; } = null!;

    [StringLength(50)]
    public string LastName { get; set; } = null!;

    public DateOnly? DOB { get; set; }

    [StringLength(100)]
    public string? Organization { get; set; }

    [StringLength(50)]
    public string? Status { get; set; }

    [StringLength(255)]
    public string Password { get; set; } = null!;

    [StringLength(50)]
    public string Role { get; set; } = null!;

    public DateOnly? MemberSince { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string? Phone { get; set; }

    [InverseProperty("Reader")]
    public virtual ICollection<tbl_Borrow_Order> tbl_Borrow_Orders { get; set; } = new List<tbl_Borrow_Order>();
}