// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace _3NF_Library.Models.Entities;

[Table("tbl_Publisher")]
public partial class tbl_Publisher
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string PublisherID { get; set; } = null!;

    [StringLength(255)]
    public string? Address { get; set; }

    public string? Description { get; set; }

    [InverseProperty("Publisher")]
    public virtual ICollection<tbl_Book> tbl_Books { get; set; } = new List<tbl_Book>();
}