// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace _3NF_Library.Models.Entities;

[Table("tbl_Category")]
[Index("ShortName", Name = "UQ__tbl_Cate__A6160FD14E284F43", IsUnique = true)]
public partial class tbl_Category
{
    [Key]
    public int CategoryID { get; set; }

    [StringLength(100)]
    public string CategoryName { get; set; } = null!;

    [StringLength(10)]
    [Unicode(false)]
    public string ShortName { get; set; } = null!;

    [InverseProperty("Category")]
    public virtual ICollection<tbl_Book> tbl_Books { get; set; } = new List<tbl_Book>();
}