// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace _3NF_Library.Models.Entities;

[Table("tbl_Author")]
[Index("LastName", "FirstName", Name = "IDX_AuthorName")]
public partial class tbl_Author
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string AuthorID { get; set; } = null!;

    [StringLength(50)]
    public string FirstName { get; set; } = null!;

    [StringLength(50)]
    public string LastName { get; set; } = null!;

    public DateOnly? DOB { get; set; }

    public string? Description { get; set; }

    [StringLength(100)]
    public string? Specialty { get; set; }

    [InverseProperty("Author")]
    public virtual ICollection<tbl_Book> tbl_Books { get; set; } = new List<tbl_Book>();
}