// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace _3NF_Library.Models.Entities;

[Table("tbl_Borrow_Order")]
public partial class tbl_Borrow_Order
{
    [Key]
    public int OrderID { get; set; }

    public int? ReaderID { get; set; }

    public DateOnly? DateBorrow { get; set; }

    public DateOnly? DateReturn { get; set; }

    public string? Notes { get; set; }

    [StringLength(50)]
    public string? OrderStatus { get; set; }

    [ForeignKey("ReaderID")]
    [InverseProperty("tbl_Borrow_Orders")]
    public virtual tbl_Reader_Account? Reader { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<tbl_Borrow_Detail> tbl_Borrow_Details { get; set; } = new List<tbl_Borrow_Detail>();
}