// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace _3NF_Library.Models.Entities;

[Table("tbl_ActivityLog")]
public partial class tbl_ActivityLog
{
    [Key]
    public int LogID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Timestamp { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ActorRole { get; set; } = null!;

    public int ActorID { get; set; }

    public string LogMessage { get; set; } = null!;
}