// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace _3NF_Library.Models.Entities;

[Table("tbl_Admin_Account")]
[Index("Username", Name = "UQ__tbl_Admi__536C85E476F99257", IsUnique = true)]
public partial class tbl_Admin_Account
{
    [Key]
    public int AdminID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Username { get; set; } = null!;

    [StringLength(255)]
    [Unicode(false)]
    public string Password { get; set; } = null!;

    [StringLength(100)]
    public string FullName { get; set; } = null!;

    [StringLength(100)]
    public string Branch { get; set; } = null!;

    public bool? IsActive { get; set; }
}