// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace _3NF_Library.Models.Entities;

[Keyless]
public partial class vw_Admin_Financial
{
    public long? TotalRevenueCollected { get; set; }

    public long? PendingRevenue { get; set; }
}