// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace _3NF_Library.Models.Entities;

[Keyless]
public partial class vw_Book_Public
{
    [StringLength(15)]
    [Unicode(false)]
    public string BookID { get; set; } = null!;

    [StringLength(50)]
    public string? Language { get; set; }

    [StringLength(200)]
    public string BookTitle { get; set; } = null!;

    [StringLength(10)]
    [Unicode(false)]
    public string? AuthorID { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string? PublisherID { get; set; }

    public int? CategoryID { get; set; }

    public DateOnly? PublishedDate { get; set; }

    public long? Value { get; set; }

    public int? CurrentlyAvailable { get; set; }

    [StringLength(100)]
    public string CategoryName { get; set; } = null!;

    [StringLength(101)]
    public string AuthorName { get; set; } = null!;

    public string? PublisherName { get; set; }
}